/**
 * exportPDF.ts
 *
 * Generates and downloads a full trip summary PDF.
 * Called from TripDetailsPage via the 3-dot menu → "Export PDF".
 *
 * Round 1 migration:
 *   - trip_metadata.itinerary → groupActivitiesByDay(trip.activities)
 *   - trip_metadata.flights/hotels → trip.saved_travel filtered by type
 *   - trip_metadata.expenses → trip.expenses
 *   - trip_metadata.checklist → trip.checklist_items
 *   - ChecklistItem: item.text (was label), item.is_checked (was checked)
 *   - ItineraryDay.date removed — days are numbered only
 *   - Flight/Hotel imports removed — use SavedTravel + cast to suggestion shape
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type {
  Trip, Activity, Expense, ChecklistItem,
  FlightSuggestion, HotelSuggestion,
} from '../types';
import { groupActivitiesByDay } from '../types';
import { convertToUSD } from './currency';
import { formatDate } from '../pages/TripDetailsPage/helpers';

// ─────────────────────────────────────────────────────────────
// CONSTANTS
// ─────────────────────────────────────────────────────────────

const BRAND_BLUE  = [37, 99, 235]   as [number, number, number];
const BRAND_GREEN = [22, 163, 74]   as [number, number, number];
const BRAND_RED   = [220, 38, 38]   as [number, number, number];
const GRAY_800    = [31, 41, 55]    as [number, number, number];
const GRAY_500    = [107, 114, 128] as [number, number, number];
const GRAY_200    = [229, 231, 235] as [number, number, number];
const WHITE       = [255, 255, 255] as [number, number, number];

const PAGE_MARGIN = 14;
const CONTENT_W   = 182;

// ─────────────────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────────────────

function pageHeight(doc: jsPDF): number {
  return (doc.internal.pageSize as { height: number }).height;
}

function ensureSpace(doc: jsPDF, y: number, needed = 20): number {
  if (y + needed > pageHeight(doc) - PAGE_MARGIN) {
    doc.addPage();
    return PAGE_MARGIN + 6;
  }
  return y;
}

function rule(doc: jsPDF, y: number, color: [number, number, number] = GRAY_200): number {
  doc.setDrawColor(...color);
  doc.setLineWidth(0.3);
  doc.line(PAGE_MARGIN, y, PAGE_MARGIN + CONTENT_W, y);
  return y + 4;
}

function sectionHeading(doc: jsPDF, y: number, title: string): number {
  y = ensureSpace(doc, y, 16);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...BRAND_BLUE);
  doc.text(title.toUpperCase(), PAGE_MARGIN, y);
  y += 1;
  return rule(doc, y, BRAND_BLUE);
}

function categoryLabel(cat: string | null): string {
  const MAP: Record<string, string> = {
    food: 'Food & Drink', transport: 'Transport', activities: 'Activities',
    shopping: 'Shopping', accommodation: 'Accommodation', other: 'Other',
  };
  return cat ? (MAP[cat] ?? cat) : 'Other';
}

function activityTypeLabel(type: Activity['type']): string {
  const MAP: Record<Activity['type'], string> = {
    flight: 'Flight', hotel: 'Hotel', activity: 'Activity',
    dining: 'Dining', transport: 'Transport',
  };
  return MAP[type] ?? type;
}

// ─────────────────────────────────────────────────────────────
// SECTION BUILDERS
// ─────────────────────────────────────────────────────────────

function addHeader(doc: jsPDF, trip: Trip): number {
  let y = PAGE_MARGIN;

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...GRAY_500);
  doc.text('Generated by TripMind', PAGE_MARGIN, y);
  const today = new Date().toLocaleDateString('en-US', { day: 'numeric', month: 'long', year: 'numeric' });
  doc.text(today, PAGE_MARGIN + CONTENT_W, y, { align: 'right' });
  y += 7;

  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...GRAY_800);
  doc.text(trip.destination, PAGE_MARGIN, y);
  y += 8;

  const dateRange = trip.start_date && trip.end_date
    ? `${formatDate(trip.start_date)} – ${formatDate(trip.end_date)}`
    : 'Dates not set';
  const duration = trip.duration_days ? `${trip.duration_days} day${trip.duration_days !== 1 ? 's' : ''}` : '';

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...GRAY_500);
  doc.text(`${dateRange}${duration ? '  ·  ' + duration : ''}`, PAGE_MARGIN, y);
  y += 5;

  if (trip.travelers_count > 0) {
    doc.text(`${trip.travelers_count} traveler${trip.travelers_count !== 1 ? 's' : ''}`, PAGE_MARGIN, y);
    y += 5;
  }

  y += 2;
  return rule(doc, y, GRAY_200) + 2;
}

function addBudgetSummary(doc: jsPDF, trip: Trip, startY: number): number {
  const budget   = trip.budget ?? 0;
  const expenses = trip.expenses;

  if (budget === 0 && expenses.length === 0) return startY;

  let y = sectionHeading(doc, startY, '  Budget Summary');

  const totalSpentUSD = expenses.reduce(
    (sum: number, e: Expense) => sum + convertToUSD(Number(e.amount), e.currency),
    0
  );
  const remaining = budget > 0 ? budget - totalSpentUSD : null;

  const rows: [string, string][] = [];
  if (budget > 0) {
    rows.push(['Total Budget (USD)', `$${budget.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`]);
  }
  if (expenses.length > 0) {
    const hasMixed = expenses.some((e) => e.currency !== 'USD');
    rows.push([
      hasMixed ? 'Total Spent (USD equiv.)' : 'Total Spent (USD)',
      `$${totalSpentUSD.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
    ]);
  }
  if (remaining !== null) {
    const overBudget = remaining < 0;
    rows.push([
      overBudget ? 'Over Budget by' : 'Remaining',
      `$${Math.abs(remaining).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
    ]);
  }

  autoTable(doc, {
    startY: y,
    body: rows,
    theme: 'plain',
    styles: { fontSize: 10, cellPadding: { top: 2, bottom: 2, left: 0, right: 4 }, textColor: GRAY_800 },
    columnStyles: {
      0: { fontStyle: 'normal', textColor: GRAY_500, cellWidth: 80 },
      1: { fontStyle: 'bold', halign: 'left' },
    },
    margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
  });

  return (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6;
}

function addItinerary(doc: jsPDF, trip: Trip, startY: number): number {
  if (trip.activities.length === 0) return startY;

  // Use groupActivitiesByDay to build the day view
  const days = groupActivitiesByDay(trip.activities);
  let y = sectionHeading(doc, startY, '  Itinerary');

  for (const day of days) {
    y = ensureSpace(doc, y, 24);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...GRAY_800);
    const dayLabel = `Day ${day.day}${day.title ? '  —  ' + day.title : ''}`;
    doc.text(dayLabel, PAGE_MARGIN, y);
    y += 5;

    if (day.activities.length === 0) {
      doc.setFontSize(9);
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(...GRAY_500);
      doc.text('No activities planned for this day.', PAGE_MARGIN + 2, y);
      y += 6;
      continue;
    }

    const rows = day.activities.map((act) => [
      act.time ?? '—',
      activityTypeLabel(act.type),
      act.title,
      act.location ?? '—',
      act.description ?? '',
    ]);

    autoTable(doc, {
      startY: y,
      head: [['Time', 'Type', 'Activity', 'Location', 'Notes']],
      body: rows,
      theme: 'striped',
      headStyles: { fillColor: BRAND_BLUE, textColor: WHITE, fontSize: 8, fontStyle: 'bold' },
      bodyStyles: { fontSize: 8, textColor: GRAY_800 },
      alternateRowStyles: { fillColor: [239, 246, 255] as [number, number, number] },
      columnStyles: {
        0: { cellWidth: 18 },
        1: { cellWidth: 22 },
        2: { cellWidth: 45 },
        3: { cellWidth: 40 },
        4: { cellWidth: 'auto' as unknown as number },
      },
      margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
    });

    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 5;
  }

  return y;
}

function addFlights(doc: jsPDF, trip: Trip, startY: number): number {
  const savedFlights = trip.saved_travel.filter((t) => t.type === 'flight');
  if (savedFlights.length === 0) return startY;

  let y = sectionHeading(doc, startY, '  Flights');

  const rows = savedFlights.map((item) => {
    const f = item.data as unknown as FlightSuggestion;
    return [
      f.flight_number ?? '—',
      f.airline ?? '—',
      `${f.from ?? '—'} → ${f.to ?? '—'}`,
      f.departure ?? '—',
      f.arrival ?? '—',
      f.cabin ?? 'Economy',
      f.notes ?? '',
    ];
  });

  autoTable(doc, {
    startY: y,
    head: [['Flight #', 'Airline', 'Route', 'Departure', 'Arrival', 'Cabin', 'Notes']],
    body: rows,
    theme: 'striped',
    headStyles: { fillColor: BRAND_BLUE, textColor: WHITE, fontSize: 8, fontStyle: 'bold' },
    bodyStyles: { fontSize: 8, textColor: GRAY_800 },
    alternateRowStyles: { fillColor: [239, 246, 255] as [number, number, number] },
    margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
  });

  return (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6;
}

function addHotels(doc: jsPDF, trip: Trip, startY: number): number {
  const savedHotels = trip.saved_travel.filter((t) => t.type === 'hotel');
  if (savedHotels.length === 0) return startY;

  let y = sectionHeading(doc, startY, '  Hotels');

  const rows = savedHotels.map((item) => {
    const h = item.data as unknown as HotelSuggestion;
    return [
      h.name ?? '—',
      `${h.area ?? ''} ${h.location ?? ''}`.trim() || '—',
      h.check_in ?? '—',
      h.check_out ?? '—',
      h.star_rating ? `${h.star_rating}★` : '—',
      h.notes ?? '',
    ];
  });

  autoTable(doc, {
    startY: y,
    head: [['Hotel', 'Location', 'Check-in', 'Check-out', 'Stars', 'Notes']],
    body: rows,
    theme: 'striped',
    headStyles: { fillColor: BRAND_BLUE, textColor: WHITE, fontSize: 8, fontStyle: 'bold' },
    bodyStyles: { fontSize: 8, textColor: GRAY_800 },
    alternateRowStyles: { fillColor: [239, 246, 255] as [number, number, number] },
    margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
  });

  return (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6;
}

function addExpenses(doc: jsPDF, trip: Trip, startY: number): number {
  const expenses = trip.expenses;
  if (expenses.length === 0) return startY;

  let y = sectionHeading(doc, startY, '  Expenses');

  const rows = [...expenses]
    .sort((a: Expense, b: Expense) => {
      // date is string | null — nulls sort to end
      if (!a.date && !b.date) return 0;
      if (!a.date) return 1;
      if (!b.date) return -1;
      return a.date.localeCompare(b.date);
    })
    .map((e: Expense) => [
      e.date ? formatDate(e.date) : '—',
      e.description ?? '—',
      categoryLabel(e.category),
      `${e.currency} ${Number(e.amount).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
    ]);

  const totalUSD = expenses.reduce(
    (sum: number, e: Expense) => sum + convertToUSD(Number(e.amount), e.currency),
    0
  );
  const hasMixed = expenses.some((e) => e.currency !== 'USD');

  autoTable(doc, {
    startY: y,
    head: [['Date', 'Description', 'Category', 'Amount']],
    body: rows,
    foot: [[
      { content: '', colSpan: 2 },
      { content: hasMixed ? 'Total (USD equiv.)' : 'Total (USD)', styles: { fontStyle: 'bold', halign: 'right' } },
      { content: `USD ${totalUSD.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, styles: { fontStyle: 'bold' } },
    ]],
    theme: 'striped',
    headStyles: { fillColor: BRAND_BLUE, textColor: WHITE,    fontSize: 8, fontStyle: 'bold' },
    footStyles: { fillColor: GRAY_200,   textColor: GRAY_800, fontSize: 8 },
    bodyStyles: { fontSize: 8, textColor: GRAY_800 },
    alternateRowStyles: { fillColor: [239, 246, 255] as [number, number, number] },
    columnStyles: {
      0: { cellWidth: 28 },
      1: { cellWidth: 'auto' as unknown as number },
      2: { cellWidth: 36 },
      3: { cellWidth: 34, halign: 'right' },
    },
    margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
  });

  return (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6;
}

function addChecklist(doc: jsPDF, trip: Trip, startY: number): number {
  const checklist: ChecklistItem[] = trip.checklist_items;
  if (checklist.length === 0) return startY;

  let y = sectionHeading(doc, startY, '  Pre-Trip Checklist');

  const rows = [...checklist]
    .sort((a, b) => a.sort_order - b.sort_order)
    .map((item) => [
      item.is_checked ? '✓' : '✗',
      item.text,
    ]);

  autoTable(doc, {
    startY: y,
    head: [['Status', 'Item']],
    body: rows,
    theme: 'plain',
    headStyles: { fillColor: BRAND_BLUE, textColor: WHITE, fontSize: 8, fontStyle: 'bold' },
    bodyStyles: { fontSize: 9, textColor: GRAY_800 },
    didParseCell: (data) => {
      if (data.column.index === 0 && data.section === 'body') {
        const checked = data.cell.raw === '✓';
        data.cell.styles.textColor = checked ? BRAND_GREEN : BRAND_RED;
        data.cell.styles.fontStyle = 'bold';
      }
    },
    columnStyles: {
      0: { cellWidth: 14, halign: 'center' },
      1: { cellWidth: 'auto' as unknown as number },
    },
    margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
  });

  return (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6;
}

function addPageNumbers(doc: jsPDF): void {
  const totalPages = (doc.internal as unknown as { pages: unknown[] }).pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...GRAY_500);
    doc.text(
      `Page ${i} of ${totalPages}`,
      PAGE_MARGIN + CONTENT_W,
      pageHeight(doc) - 6,
      { align: 'right' }
    );
  }
}

// ─────────────────────────────────────────────────────────────
// MAIN EXPORT
// ─────────────────────────────────────────────────────────────

export function exportTripPDF(trip: Trip): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  let y = addHeader(doc, trip);
  y = addBudgetSummary(doc, trip, y);
  y = addItinerary(doc, trip, y);
  y = addFlights(doc, trip, y);
  y = addHotels(doc, trip, y);
  y = addExpenses(doc, trip, y);
  y = addChecklist(doc, trip, y);

  addPageNumbers(doc);

  const slug = trip.destination
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
  const date = new Date().toISOString().split('T')[0];
  doc.save(`tripmind-${slug}-${date}.pdf`);
}