"""normalize_trip_data

Revision ID: a58a4bc70073
Revises: 
Create Date: 2026-04-11 23:11:22.145039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a58a4bc70073'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('trips', sa.Column('cover_image_url', sa.Text(), nullable=True))
    op.add_column('trips', sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('trips', sa.Column('ai_alerts', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('trips', sa.Column('ai_recommendations', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.alter_column('trips', 'travelers_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trips', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('trips', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.create_index('ix_trips_user_updated', 'trips', ['user_id', 'updated_at'], unique=False)
    op.drop_constraint(op.f('trips_user_id_fkey'), 'trips', type_='foreignkey')
    op.create_foreign_key(None, 'trips', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('trips', 'trip_metadata')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('trips', sa.Column('trip_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.create_foreign_key(op.f('trips_user_id_fkey'), 'trips', 'users', ['user_id'], ['id'])
    op.drop_index('ix_trips_user_updated', table_name='trips')
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.alter_column('trips', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('trips', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('trips', 'travelers_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('trips', 'ai_recommendations')
    op.drop_column('trips', 'ai_alerts')
    op.drop_column('trips', 'preferences')
    op.drop_column('trips', 'cover_image_url')
    op.drop_column('trips', 'notes')
    # ### end Alembic commands ###
